  !---------------------------------------------------------
  ! Global definitions of constants for Path Integrals
  ! * Values are from CODATA (physics.nist.gov/constants)
  !---------------------------------------------------------
      real(8) Kboltz,Kboltz_SI,toA,echarge,emass
      real(8) ToDebye,toK,hbar,toKjmol,tobar,tokgcm3,tofs
      integer imaxbin,nbondmax,iskip,maxnab
      parameter (Kboltz = 3.166829d-6)
      parameter (Kboltz_SI = 1.3806505d-23)
      parameter (toA = 0.5291772108d0)
      parameter (echarge = 1.60217653d-19)
      parameter (emass = 9.1093826d-31)
      parameter (ToDebye = 3.336d-30)
      parameter (toK = 3.157733d+5)
      parameter (hbar = 1.d0)
      parameter (toKjmol = 2625.49963d0)
      parameter (tobar = 2.9421d+8)
      parameter (tokgcm3 = 6.147323129d-3)
      parameter (tofs = 41.341373d0)
      parameter (imaxbin = 500)
      parameter (iskip = 1)
      parameter (maxnab = 200)
      parameter (nbondmax = 5000)



